name: Cypress Scans
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1-5'
jobs:
  cypress:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Cypress
        run: npm install -g cypress@13
      - name: Install
        run: npm ci
      - name: Run Tests
        run: npm run cy:run:record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
